version: "3.9"

services:
  odoo:
    image: novobidevops/odoo:14
    # build: ./box
    ports:
      - "8069:8069"
    volumes:
      - ./:/opt/odoo
      - odoo_data:/root/.local/share/Odoo
    depends_on:
      - postgres
      - nginx
    restart: unless-stopped
    tty: true
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./box/odoo_nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    tty: true
  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    tty: true

volumes:
  odoo_data:
  postgres_data:
